### ISSUE TITLE
Could you please add the latest version 1.4.2

### ISSUE THREAD

**Issue by metaman** [webjars/packery#1]

**Comment by metaman** [comment]
Much appreciated. Can't see it yet on the webjar 'classic' page? Does it take it long to be updated?

**Comment by jamesward** [comment]
It should be available on Maven Central now (so you can use it). But it will take a few hours to show up on webjars.org.

**Comment by metaman** [comment]
Hi James, sorry to be a pain :)  It is possible to include the dist folders in both the packery and draggabilly repos into the webjar as this is where the packaged/minified versions of the libraries are located?  These packaged versions include some of the repo owner's other dependencies which otherwise would have to be pulled into webjars as well eg..classie..

**Comment by jamesward** [comment]
How does this look: https://github.com/webjars/packery/pull/2/files

**Comment by metaman** [comment]
Looks great thanks.
